### ISSUE TITLE
Use G2 function in createG2

### ISSUE THREAD

**Issue by karimhossenbux** [fireyy/g2-vue#3]
Hey! Thank you for this useful wrapper.

I was wondering how could I use other function un G2 (like G2.Frame) in the createG2 function ?
I'm trying to get this example working: https://antv.alipay.com/g2/demo/07-k/k-chart-01.html
I have something like this:

```
import createG2 from 'g2-vue'

const Chart = createG2(chart => {
  axios.get('https://raw.githubusercontent.com/antvis/antvis.github.io/master/static/data/candleSticks.json')
    .then(function (response) {
      var Frame = G2.Frame
      var frame = new Frame(response.data)
    })
    .catch(function (error) {
      console.log(error)
    })
})
```

**Comment by fireyy** [comment]
You can import G2, and use `G2.xxxx`, like:

```
import G2 from 'g2'
import createG2 from 'g2-vue'

const Chart = createG2(chart => {
  axios.get('https://raw.githubusercontent.com/antvis/antvis.github.io/master/static/data/candleSticks.json')
    .then(function (response) {
      var Frame = G2.Frame
      var frame = new Frame(response.data)
    })
    .catch(function (error) {
      console.log(error)
    })
})
```

**Comment by karimhossenbux** [comment]
I'm having an issue when I want to get a value from data() in the createG2 instance but can't.
Do you have any idea?

Could you explain me why createG2() need to be outside of export? I'm new to VueJS, if you could point me out to that pattern it would be great too :)

```
import G2 from 'g2'
import createG2 from 'g2-vue'

const Chart = createG2(chart => {
  console.log('from createG2()', this.market)
})

xport default {
  components: { CandleStickTest },
  mounted () {
    console.log('from mounted()', this.market)
  },
  props: ['m'],
  data () {
    return {
      candles: candles,
      market: this.m
    }
  }
}
```

from mounted() is print fine
from createG2() is undefined

edit:

Nevermind, found a way of passing the var from template with plot-cfg 
console.log('from createG2()', chart._attrs.plotCfg.market)

**Comment by fireyy** [comment]
@karimhossenbux Sorry for response late, 👍
